### ISSUE TITLE
Update Xcode project version in step with release versions for the develop branch

### ISSUE THREAD

**Issue by cailyoung** [CommandPost/CommandPost-App#36]
As per subject, otherwise when building from source off the develop branch the updater prompts you to update. Alternately disable the version check in a develop target?

**Comment by cailyoung** [comment]
Actually, looks like I was a few commits behind. Apologies.

**Comment by latenitefilms** [comment]
As part of releasing a new beta to the public I always increase the Xcode version at the same time as updating the `appcast.xml`. So once a new beta comes out, the version in the CommandPost-App master branch should always be greater than the public release version.
